margin = 80

always_for_in = true

whitespace_typedefs = true

whitespace_ops_in_indices = true

import_to_using = true

pipe_to_function_call = true

short_to_long_function_def = true

force_long_function_def = true

format_docstrings = true

separate_kwargs_with_semicolon = true
